## Numpy processing time

In [7]:
import numpy as np
import time
from numpy.random import rand

In [27]:
N = 150
matA = np.array(rand(N,N))
matB = np.array(rand(N,N))
matC = np.array([[0]*N for _ in range(N)])


In [28]:
start = time.time()
for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]
print("result: %f[sec]" % float(time.time()-start))

result: 2.746244[sec]


In [29]:
start2 = time.time()
matC = np.dot(matA, matB)
print("result: %f[sec]" % float(time.time()-start2))

result: 0.000314[sec]


## 1-Dimension array

In [32]:
storages = [24, 3, 4, 23, 10, 12]
print (storages)
np_storages = np.array(storages)
print(type(np_storages))

[24, 3, 4, 23, 10, 12]
<class 'numpy.ndarray'>


In [33]:
storages = [1,2,3,4]
new_storages = []
for n in storages:
    n += n
    new_storages.append(n)
print(new_storages)

[2, 4, 6, 8]


In [38]:
import numpy as np
arr = np.array([2,5,3,4,8])
print(arr + arr)
print(arr - arr)
print(arr ** 3)
print(1/arr)

[ 4 10  6  8 16]
[0 0 0 0 0]
[  8 125  27  64 512]
[0.5        0.2        0.33333333 0.25       0.125     ]


## Index reference and slice

In [42]:
arr = np.arange(10)
print(arr)
arr[0:3] = 1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 1 1 3 4 5 6 7 8 9]


In [45]:
arr = np.arange(10)
print(arr[3:6])

[3 4 5]


In [46]:
arr[3:6] = 24
print(arr)

[ 0  1  2 24 24 24  6  7  8  9]


## copy

In [51]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
arr2 = arr1
arr2[0] = 100
print(arr1)

[1 2 3 4 5]
[100   2   3   4   5]


In [54]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1.copy()
arr2[0] = 100
print(arr2)
print(arr1)

[100   2   3   4   5]
[1 2 3 4 5]


## view , copy

In [62]:
#1. list

In [63]:
arr_list = [x for x in range(10)]
print("arr_list: ", arr_list)

arr_list:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [64]:
arr_list_copy = arr_list[:]
arr_list_copy[0] = 100
print("arr_list: ", arr_list)
print("arr_list: ", arr_list_copy)

arr_list:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr_list:  [100, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [71]:
#2. ndarray

In [8]:
arr_NumPy = np.arange(10)
print("arr_NumPy: ", arr_NumPy)

arr_NumPy:  [0 1 2 3 4 5 6 7 8 9]


In [9]:
arr_NumPy_view = arr_NumPy[:]
arr_NumPy_view[0] = 100
print("arr_NumPy: ", arr_NumPy)

arr_NumPy:  [100   1   2   3   4   5   6   7   8   9]


In [10]:
arr_NumPy = np.arange(10)
arr_NumPy_view = arr_NumPy[:]
arr_NumPy_view[0] = 100
print("arr_NumPy: ", arr_NumPy)

arr_NumPy:  [100   1   2   3   4   5   6   7   8   9]


In [11]:
arr_NumPy = np.arange(10)
arr_NumPy_view = arr_NumPy[:].copy()
arr_NumPy_view[0] = 100
print("arr_NumPy: ", arr_NumPy)

arr_NumPy:  [0 1 2 3 4 5 6 7 8 9]


## Bool Index reference

In [15]:
arr = np.array([2,4,6,7])
p;rint
print(arr[np.array([True, True, True, False])])

[2 4 6]


In [18]:
arr = np.array([2,4,6,7])
print(arr[arr%3==1])
print(arr[arr%2==0])

[4 7]
[2 4 6]


In [20]:
arr = np.array([4, -9, 16, -4, 20])
print(arr)

[ 4 -9 16 -4 20]


In [25]:
arr_abs = np.abs(arr)
print(arr_abs)
print(np.exp(arr))
print(np.sqrt(arr))

[ 4  9 16  4 20]
[5.45981500e+01 1.23409804e-04 8.88611052e+06 1.83156389e-02
 4.85165195e+08]
[2.                nan 4.                nan 4.47213595]


/home/max/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in sqrt
  after removing the cwd from sys.path.


## 집합 함수

In [26]:
import numpy as np

In [27]:
arr1 = [2,5,7,9,5,2]
arr2 = [2,5,8,3,1]

In [29]:
new_arr1 = np.unique(arr1)
print(new_arr1)

[2 5 7 9]


In [34]:
# 합집합
print(np.union1d(new_arr1, arr2))

[1 2 3 5 7 8 9]


In [36]:
# 교집합
print(np.intersect1d(new_arr1, arr2))

[2 5]


In [37]:
#차집합
print(np.setdiff1d(new_arr1, arr2))

[7 9]


## 난수

In [42]:
from numpy.random import randint
arr1 = randint(0, 11, (5,2))
print(arr1)

[[ 2  9]
 [ 4  9]
 [ 3 10]
 [ 3 10]
 [ 2  8]]


In [45]:
arr2 = np.random.rand(3)
print(arr2)

[0.39009825 0.12544211 0.78560954]


## NumPy 2차원 배열

In [48]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [49]:
print(arr.shape)

(2, 4)


In [50]:
print (arr.reshape(4,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [51]:
print(arr[1])

[5 6 7 8]


In [52]:
print(arr[1,2])

7


In [53]:
print(arr[1,1:])

[6 7 8]


In [54]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
print(arr[0,2])

3


In [58]:
print(arr[1:, :2])

[[4 5]
 [7 8]]


## axis

In [62]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))


21
[5 7 9]
[ 6 15]


In [63]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.sum(axis=1))

[ 6 15 24]


In [65]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr[[1,3,0]])

[[3 4]
 [7 8]
 [1 2]]


In [68]:
arr = np.arange(25).reshape(5,5)
print(arr[[1,3,0]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


##  전치 행렬

In [71]:
arr = np.arange(10).reshape(2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [72]:
print(arr.T)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [73]:
arr = np.array([15,30,5])
arr.argsort()

array([2, 0, 1])

In [74]:
arr = np.array([[8,4,2],[3,5,1]])
arr.argsort()

array([[2, 1, 0],
       [2, 0, 1]])

In [75]:
np.sort(arr)

array([[2, 4, 8],
       [1, 3, 5]])

In [77]:
arr.sort(1)
print(arr)

[[2 4 8]
 [1 3 5]]


## 행렬 계산

In [79]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(np.dot(arr,arr))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [81]:
vec = arr.reshape(9)
print(vec)

[0 1 2 3 4 5 6 7 8]


In [82]:
print(np.linalg.norm(vec))

14.2828568570857


## 통계 함수

In [85]:
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [86]:
print(arr.mean(axis=0))

[5. 6. 7. 8. 9.]


In [87]:
print(arr.sum(axis=1))

[10 35 60]


In [88]:
print(arr.min())

0


In [89]:
print(arr.max())

14


In [90]:
print(arr.argmax(axis=0))

[2 2 2 2 2]


## 브로드캐스트

In [91]:
x = np.arange(6).reshape(2,3)
print(x)

[[0 1 2]
 [3 4 5]]


In [92]:
print(x+1)

[[1 2 3]
 [4 5 6]]


In [94]:
x = np.arange(15).reshape(3,5)
y = np.array([np.arange(5)])

In [97]:
z = x-y
print(z)

[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]


In [102]:
np.random.seed(100)
arr = np.random.randint(0,31,(5,3))
print(arr)

[[ 8 24  3]
 [ 7 23 15]
 [16 10 30]
 [20  2 21]
 [ 2  2 14]]


In [103]:
arr= arr.T
print(arr)

[[ 8  7 16 20  2]
 [24 23 10  2  2]
 [ 3 15 30 21 14]]


In [105]:
arr1 = arr[:, 1:4]
print(arr1)

[[ 7 16 20]
 [23 10  2]
 [15 30 21]]


In [107]:
arr1.sort(0)
print(arr1)

[[ 7 10  2]
 [15 16 20]
 [23 30 21]]


In [108]:
print(arr1.mean(axis=0))

[15.         18.66666667 14.33333333]


## TT

In [109]:
np.random.seed(0)

In [117]:
def make_image(m,n):
    image = np.random.randint(0,6,(m,n))
    return image

In [128]:
def change_little(matrix):
    shape = matrix.shape
    for i in range(shape[0]):
        for j in range(shape[1]):
            if np.random.randint(0,2)==1:
                matrix[i][j] = np.random.randint(0,6,1)
    return matrix

In [129]:
image1 = make_image(3,3)
print(image1)
print()

[[0 1 1]
 [1 0 2]
 [4 3 3]]



In [132]:
image2 = change_little(np.copy(image1))
print(image2)
print()

[[3 1 1]
 [0 0 5]
 [4 2 3]]



In [135]:
image3 = image2 - image1
print(image3)
print()

[[ 3  0  0]
 [-1  0  3]
 [ 0 -1  0]]



In [136]:
image3 = np.abs(image3)
print(image3)

[[3 0 0]
 [1 0 3]
 [0 1 0]]
