## Numpy processing time

In [26]:
import numpy as np
import time
from numpy.random import rand

In [27]:
N = 150
matA = np.array(rand(N,N))
matB = np.array(rand(N,N))
matC = np.array([[0]*N for _ in range(N)])


In [28]:
start = time.time()
for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]
print("result: %f[sec]" % float(time.time()-start))

result: 2.746244[sec]


In [29]:
start2 = time.time()
matC = np.dot(matA, matB)
print("result: %f[sec]" % float(time.time()-start2))

result: 0.000314[sec]


## 1-Dimension array

In [32]:
storages = [24, 3, 4, 23, 10, 12]
print (storages)
np_storages = np.array(storages)
print(type(np_storages))

[24, 3, 4, 23, 10, 12]
<class 'numpy.ndarray'>


In [33]:
storages = [1,2,3,4]
new_storages = []
for n in storages:
    n += n
    new_storages.append(n)
print(new_storages)

[2, 4, 6, 8]


In [38]:
import numpy as np
arr = np.array([2,5,3,4,8])
print(arr + arr)
print(arr - arr)
print(arr ** 3)
print(1/arr)

[ 4 10  6  8 16]
[0 0 0 0 0]
[  8 125  27  64 512]
[0.5        0.2        0.33333333 0.25       0.125     ]


## Index reference and slice

In [42]:
arr = np.arange(10)
print(arr)
arr[0:3] = 1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 1 1 3 4 5 6 7 8 9]


In [45]:
arr = np.arange(10)
print(arr[3:6])

[3 4 5]


In [46]:
arr[3:6] = 24
print(arr)

[ 0  1  2 24 24 24  6  7  8  9]


## copy

In [51]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
arr2 = arr1
arr2[0] = 100
print(arr1)

[1 2 3 4 5]
[100   2   3   4   5]


In [54]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1.copy()
arr2[0] = 100
print(arr2)
print(arr1)

[100   2   3   4   5]
[1 2 3 4 5]


## view , copy

In [62]:
#1. list

In [63]:
arr_list = [x for x in range(10)]
print("arr_list: ", arr_list)

arr_list:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [64]:
arr_list_copy = arr_list[:]
arr_list_copy[0] = 100
print("arr_list: ", arr_list)
print("arr_list: ", arr_list_copy)

arr_list:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr_list:  [100, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [71]:
#2. ndarray

In [72]:
arr_NumPy = np.arange(10)
print("arr_NumPy: ", arr_NumPy)

arr_NumPy:  [0 1 2 3 4 5 6 7 8 9]


In [73]:
arr_NumPy_view = arr_NumPy[:]
arr_NumPy_view[0] = 100
print("arr_NumPy: ", arr_NumPy)

arr_NumPy:  [100   1   2   3   4   5   6   7   8   9]


In [74]:
arr_NumPy = np.arange(10)
arr_NumPy_view = arr_NumPy[:]
arr_NumPy_view[0] = 100
print("arr_NumPy: ", arr_NumPy)

arr_NumPy:  [100   1   2   3   4   5   6   7   8   9]
